POST http://localhost:3000/api/conversations HTTP/1.1
content-Type: application/json

{
    "senderId":"4GXiWy64HePCxozKRTbx07LU1bb2",
    "receiverId":"UCmcA3zzgwcVHBdijKglvkZYkmq1"
}
###
POST http://localhost:3000/api/messages HTTP/1.1
content-Type: application/json

{
    "conversationId":"7b32adf8-9e7a-4bce-9283-108adacaed02",
    "sender":"4GXiWy64HePCxozKRTbx07LU1bb2",
    "text": "Hello! lol"
}
###
GET http://localhost:3000/api/conversations/4GXiWy64HePCxozKRTbx07LU1bb2 HTTP/1.1

###
GET http://localhost:3000/api/messages/7b32adf8-9e7a-4bce-9283-108adacaed02 HTTP/1.1
###
POST http://localhost:3000/api/newUser HTTP/1.1
content-Type: application/json

{
    "uid":"4GXiWy64HePCxozKRTbx07LU1bb2",
    "name":"wfwef",
    "email": "cdsvdv",
    "avatar": "fwef"
}