import Head from "next/head";
// import Messenger from "../components/messenger";
import HomePage from "../components/homePage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-5/6 flex justify-center">
        <HomePage />
      </main>
    </>
  );
}
